on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n PratikContainerRegis -g PratikContainerRegis9249-rg --location "Southeast Asia" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n PratikContainerRegis --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n PratikContainerRegis --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n PratikContainerRegis --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: pratikcontainerregis.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/10.0.0.10" -f  "10.0.0.10/Dockerfile" -t pratikcontainerregis.azurecr.io/iibclus:${{ github.sha }}
        docker push pratikcontainerregis.azurecr.io/iibclus:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_iibclus_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep iib-clus8c18 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace iib-clus8c18`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: iib-clus8c18
        container-registry-url: pratikcontainerregis.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: iibclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: iib-clus8c18
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          pratikcontainerregis.azurecr.io/iibclus:${{ github.sha }}
        imagepullsecrets: |
          iibclusdockerauth